# Generated by Django 5.0.1 on 2025-07-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0009_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="mobile_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mtn", "MTN"),
                    ("airtel", "Airtel"),
                    ("vodafone", "Vodafone"),
                    ("tigo", "Tigo"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("paypal", "PayPal"), ("mobile_money", "Mobile Money")],
                default="paypal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_verified",
            field=models.BooleanField(default=False),
        ),
    ]
